version: '3.8'

services:
  tiemtra-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tiemtra-server
    environment:
      SA_PASSWORD: "Grunt.0514"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - apinetwork

  tiemtra-api:
    build:
      context: .
      dockerfile: src/TiemTra_Api/Dockerfile
    container_name: tiemtra-api
    depends_on:
      - tiemtra-server
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Database=GStore24;User=sa;Password=Grunt.0514;TrustServerCertificate=True;"
    ports:
      - "5001:80"
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge
