version: '3.8'

services:
  tiemtra-api:
    build:
      context: .
      dockerfile: src/TiemTra_Api/Dockerfile
    container_name: tiemtra-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=GStore24;User=sa;Password=Grunt.0514;TrustServerCertificate=True;"
    ports:
      - "5001:80"
    networks:
      - tiemtra-network

networks:
  tiemtra-network:
    driver: bridge
